---@meta

---@enum ImportFolderType
ImportFolderType = {
    Excluded = "Excluded",
    Source = "Source",
    Destination = "Destination",
    Both = "Both"
}

---@enum AnimeType
AnimeType = {
    Movie = "Movie",
    OVA = "OVA",
    TVSeries = "TVSeries",
    TVSpecial = "TVSpecial",
    Web = "Web",
    Other = "Other"
}

---@enum EpisodeType
EpisodeType = {
    Episode = "Episode",
    Credits = "Credits",
    Special = "Special",
    Trailer = "Trailer",
    Parody = "Parody",
    Other = "Other"
}

---@enum TitleType
TitleType = {
    None = "None",
    Main = "Main",
    Official = "Official",
    Short = "Short",
    Synonym = "Synonym",
    TitleCard = "TitleCard",
    KanjiReading = "KanjiReading"
}

---@enum Language
Language = {
    None = "None",
    Unknown = "Unknown",
    English = "English",
    Romaji = "Romaji",
    Japanese = "Japanese",
    Afrikaans = "Afrikaans",
    Arabic = "Arabic",
    Bangladeshi = "Bangladeshi",
    Bulgarian = "Bulgarian",
    FrenchCanadian = "FrenchCanadian",
    Czech = "Czech",
    Danish = "Danish",
    German = "German",
    Greek = "Greek",
    Spanish = "Spanish",
    Estonian = "Estonian",
    Finnish = "Finnish",
    French = "French",
    Galician = "Galician",
    Hebrew = "Hebrew",
    Hungarian = "Hungarian",
    Italian = "Italian",
    Korean = "Korean",
    Lithuanian = "Lithuanian",
    Mongolian = "Mongolian",
    Malaysian = "Malaysian",
    Dutch = "Dutch",
    Norwegian = "Norwegian",
    Polish = "Polish",
    Portuguese = "Portuguese",
    BrazilianPortuguese = "BrazilianPortuguese",
    Romanian = "Romanian",
    Russian = "Russian",
    Slovak = "Slovak",
    Slovenian = "Slovenian",
    Serbian = "Serbian",
    Swedish = "Swedish",
    Thai = "Thai",
    Turkish = "Turkish",
    Ukrainian = "Ukrainian",
    Vietnamese = "Vietnamese",
    Chinese = "Chinese",
    ChineseSimplified = "ChineseSimplified",
    ChineseTraditional = "ChineseTraditional",
    Pinyin = "Pinyin",
    Latin = "Latin",
    Albanian = "Albanian",
    Basque = "Basque",
    Bengali = "Bengali",
    Bosnian = "Bosnian",
    Amharic = "Amharic",
    Armenian = "Armenian",
    Azerbaijani = "Azerbaijani",
    Belarusian = "Belarusian",
    Catalan = "Catalan",
    Chichewa = "Chichewa",
    Corsican = "Corsican",
    Croatian = "Croatian",
    Divehi = "Divehi",
    Esperanto = "Esperanto",
    Fijian = "Fijian",
    Georgian = "Georgian",
    Gujarati = "Gujarati",
    HaitianCreole = "HaitianCreole",
    Hausa = "Hausa",
    Icelandic = "Icelandic",
    Igbo = "Igbo",
    Indonesian = "Indonesian",
    Irish = "Irish",
    Javanese = "Javanese",
    Kannada = "Kannada",
    Kazakh = "Kazakh",
    Khmer = "Khmer",
    Kurdish = "Kurdish",
    Kyrgyz = "Kyrgyz",
    Lao = "Lao",
    Latvian = "Latvian",
    Luxembourgish = "Luxembourgish",
    Macedonian = "Macedonian",
    Malagasy = "Malagasy",
    Malayalam = "Malayalam",
    Maltese = "Maltese",
    Maori = "Maori",
    Marathi = "Marathi",
    MyanmarBurmese = "MyanmarBurmese",
    Nepali = "Nepali",
    Oriya = "Oriya",
    Pashto = "Pashto",
    Persian = "Persian",
    Punjabi = "Punjabi",
    Quechua = "Quechua",
    Samoan = "Samoan",
    ScotsGaelic = "ScotsGaelic",
    Sesotho = "Sesotho",
    Shona = "Shona",
    Sindhi = "Sindhi",
    Sinhala = "Sinhala",
    Somali = "Somali",
    Swahili = "Swahili",
    Tajik = "Tajik",
    Tamil = "Tamil",
    Tatar = "Tatar",
    Telugu = "Telugu",
    Turkmen = "Turkmen",
    Uighur = "Uighur",
    Uzbek = "Uzbek",
    Welsh = "Welsh",
    Xhosa = "Xhosa",
    Yiddish = "Yiddish",
    Yoruba = "Yoruba",
    Zulu = "Zulu",
    Hindi = "Hindi",
    Filipino = "Filipino",
    KoreanTranscription = "KoreanTranscription",
    ThaiTranscription = "ThaiTranscription",
    Urdu = "Urdu",
}

---@enum RelationType
RelationType = {
    Other = "Other",
    SameSetting = "SameSetting",
    AlternativeSetting = "AlternativeSetting",
    AlternativeVersion = "AlternativeVersion",
    SharedCharacters = "SharedCharacters",
    Prequel = "Prequel",
    MainStory = "MainStory",
    FullStory = "FullStory",
    Sequel = "Sequel",
    SideStory = "SideStory",
    Summary = "Summary"
}
