<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Shoko.Abstractions" Version="6.0.0-alpha.43" />
        <PackageVersion Include="KeraLua" Version="1.4.9" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
        <PackageVersion Include="NLua" Version="1.7.8" />
        <PackageVersion Include="Moq" Version="4.20.72" />
        <PackageVersion Include="MSTest" Version="4.1.0" />
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    </ItemGroup>
</Project>
