using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LuaNamesGenerator;

/// <summary>
/// Emits <c>*Names</c> companion classes for each <c>*Table</c> schema class.
/// The navigation DSL allows Lua path strings to be built in a compiler-checked, type-safe
/// manner (e.g. <c>EnvNames.anime.relations[1].type</c> produces the string
/// <c>"anime.relations[1].type"</c>). This replaces the hand-written table classes that
/// previously doubled as both schema and navigation.
/// </summary>
[Generator]
public class NamesGenerator : IIncrementalGenerator
{
    private const string Ns = "LuaRenamer.LuaEnv";
    private const string Bt = "global::LuaRenamer.LuaEnv.BaseTypes";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider.Select(static (compilation, _) => Build(compilation));
        context.RegisterSourceOutput(source, static (spc, src) =>
        {
            if (src is not null)
                spc.AddSource("LuaNames.g.cs", SourceText.From(src, Encoding.UTF8));
        });
    }

    private static string? Build(Compilation compilation)
    {
        var ns = GetNamespace(compilation.GlobalNamespace, Ns.Split('.'));
        if (ns is null)
            return null;

        var types = ns.GetTypeMembers().Where(t => t.TypeKind == TypeKind.Class).ToList();

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n\n");
        sb.Append("namespace LuaRenamer.LuaEnv.Names;\n\n");

        foreach (var t in types.OrderBy(t => t.Name, StringComparer.Ordinal))
        {
            var isTable = InheritsFromLuaTableWriter(t);

            if (isTable)
                EmitNames(sb, t);
        }

        return sb.ToString();
    }

    private static void EmitNames(StringBuilder sb, INamedTypeSymbol type)
    {
        var namesClass = TableToNames(type.Name);

        sb.Append($"public sealed class {namesClass} : {Bt}.Table\n{{\n");

        foreach (var member in type.GetMembers())
        {
            switch (member)
            {
                // Function binding property: LuaFunctionRef<TDelegate> with [LuaField].
                // Must be matched before the generic [LuaField] data case since these props also carry [LuaField].
                case IPropertySymbol prop when GetAttr(prop, "LuaFieldAttribute") is not null
                    && prop.Type is INamedTypeSymbol { Name: "LuaFunctionRef" or "LuaMethodRef", TypeArguments.Length: 1 } funcRef
                    && funcRef.TypeArguments[0] is INamedTypeSymbol del
                    && del.DelegateInvokeMethod is { } invoke:
                {
                    var pars = new List<string>();
                    var args = new List<string>();
                    foreach (var param in invoke.Parameters)
                    {
                        var isNull = param.Type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T }
                            || param.NullableAnnotation == NullableAnnotation.Annotated;
                        var name = param.Name;
                        pars.Add(isNull ? $"string? {name} = null" : $"string {name}");
                        args.Add(name);
                    }
                    var sep = funcRef.Name == "LuaMethodRef" ? ":" : ".";
                    var body = $"GetFunc([{string.Join(", ", args)}], '{sep}')";
                    sb.Append($"    public string {prop.Name}({string.Join(", ", pars)}) => {body};\n");
                    break;
                }
                // Bound data field: [LuaField] on a property.
                case IPropertySymbol prop when GetAttr(prop, "LuaFieldAttribute") is not null:
                {
                    EmitNavProp(sb, prop.Name, prop.Type);
                    break;
                }
            }
        }

        sb.Append("}\n\n");
    }

    private static void EmitNavProp(StringBuilder sb, string name, ITypeSymbol ts)
    {
        var getCall = "Get()";

        // Nullable<T> wrapping a struct (LuaRef<T>?, long?, enum?, bool?)
        if (ts is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullSym)
        {
            var inner = nullSym.TypeArguments[0];
            if (inner is INamedTypeSymbol { Name: "LuaRef", TypeArguments.Length: 1 } luaRef)
            {
                // LuaRef<T>? — always emitted as a navigable (non-nullable) nav property.
                var navType = TableToNames(luaRef.TypeArguments[0].Name);
                sb.Append($"    public {navType} {name} => new() {{ Fn = {getCall} }};\n");
                return;
            }
            // Scalar? (long?, bool?, enum?) — leaf string.
            sb.Append($"    public string {name} => {getCall};\n");
            return;
        }

        if (ts is INamedTypeSymbol named)
        {
            switch (named.Name)
            {
                case "LuaRef" when named.TypeArguments.Length == 1:
                {
                    var navType = TableToNames(named.TypeArguments[0].Name);
                    sb.Append($"    public {navType} {name} => new() {{ Fn = {getCall} }};\n");
                    return;
                }
                case "LuaArray" when named.TypeArguments.Length == 1:
                {
                    var elem = named.TypeArguments[0];
                    if (elem is INamedTypeSymbol { Name: "LuaRef", TypeArguments.Length: 1 } elemRef)
                    {
                        var elemNav = TableToNames(elemRef.TypeArguments[0].Name);
                        sb.Append($"    public {Bt}.ArrayTable<{elemNav}> {name} => new() {{ Fn = {getCall} }};\n");
                        return;
                    }
                    // LuaArray<scalar> — leaf string.
                    sb.Append($"    public string {name} => {getCall};\n");
                    return;
                }
                case "LuaMap":
                    sb.Append($"    public string {name} => {getCall};\n");
                    return;
                case "LuaEnumRef" when named.TypeArguments.Length == 1:
                {
                    var enumType = named.TypeArguments[0];
                    var fqEnum = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var pascalName = char.ToUpper(name[0]) + name.Substring(1); // camelCase → PascalCase
                    sb.Append($"    public {Bt}.EnumTable<{fqEnum}> {pascalName} => new() {{ Fn = {getCall} }};\n");
                    return;
                }
            }
        }

        // Scalars (long, double, bool, string, string?, enum) — leaf string.
        sb.Append($"    public string {name} => {getCall};\n");
    }

    private static string TableToNames(string name) =>
        name.EndsWith("Table") ? name.Substring(0, name.Length - 5) + "Names" : name + "Names";

    private static AttributeData? GetAttr(ISymbol s, string attrName) =>
        s.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attrName);

    private static bool InheritsFromLuaTableWriter(INamedTypeSymbol type)
    {
        var current = type.BaseType;
        while (current is not null)
        {
            if (current.Name == "LuaTableWriter") return true;
            current = current.BaseType;
        }
        return false;
    }

    private static INamespaceSymbol? GetNamespace(INamespaceSymbol root, IEnumerable<string> parts)
    {
        var current = root;
        foreach (var part in parts)
        {
            current = current.GetNamespaceMembers().FirstOrDefault(n => n.Name == part);
            if (current is null)
                return null;
        }
        return current;
    }
}
