using System.Reflection;
using System.Text;
using LuaRenamer.LuaEnv;

namespace LuaRenamer.DefsGenerator;

/// <summary>
/// Emits the <c>*Names</c> navigation DSL — one companion class per <see cref="ILuaModel"/> record, letting
/// Lua path strings be built in a compiler-checked way (<c>EnvNames.anime.relations[1].type</c> produces
/// <c>"anime.relations[1].type"</c>). Consumed by the test suite to write Lua snippets that stop compiling
/// when the schema moves under them.
/// </summary>
/// <remarks>
/// Driven by the same reflection over <see cref="ILuaModel"/> that <see cref="ModelDefsGenerator"/> uses, so
/// the two views of the schema cannot disagree about what a property is (see <see cref="SchemaReflection"/>).
/// The base types (<c>NamesNode</c>, <c>NamesArray&lt;T&gt;</c>, <c>NamesEnum&lt;T&gt;</c>) are hand-written
/// source in LuaEnv rather than a second emitted file.
/// </remarks>
public sealed class ModelNamesGenerator
{
    // Namespace/base of the emitted DSL.
    private const string Bt = "global::LuaRenamer.LuaEnv.Names";

    // Shared across the whole run; it is a cache, and it is not thread-safe.
    private readonly NullabilityInfoContext _nullability = new();

    /// <summary>The complete generated source file. Performs no I/O — <c>Program</c> writes it.</summary>
    public string GenerateNames()
    {
        var sb = new StringBuilder();
        _ = sb.Append("// <auto-generated/>\n#nullable enable\n\n");
        _ = sb.Append("namespace LuaRenamer.LuaEnv.Names;\n\n");

        // Ordered by CLR type name — deliberately not defs.lua's stripped-name order (see SchemaReflection).
        // EnvModel is included here (it is the DSL root) even though defs.lua's class section excludes it.
        foreach (Type? type in SchemaReflection.ModelTypes().OrderBy(t => t.Name, StringComparer.Ordinal))
            EmitNames(sb, type);

        return sb.ToString();
    }

    private void EmitNames(StringBuilder sb, Type type)
    {
        _ = sb.Append($"public sealed class {ModelToNames(type.Name)} : {Bt}.NamesNode\n{{\n");

        foreach ((PropertyInfo? prop, LuaFieldAttribute? field) in SchemaReflection.LuaFields(type))
        {
            if (SchemaReflection.ContractOf(prop.PropertyType) is { } contract)
                EmitCallable(sb, prop.Name, contract, field.Method ? ':' : '.');
            else
                EmitNavProp(sb, prop.Name, prop.PropertyType);
        }

        _ = sb.Append("}\n\n");
    }

    /// <summary>
    /// A callable field becomes a method taking one string per Lua parameter. Optional Lua parameters (a
    /// nullable CLR parameter) default to null and are dropped from the rendered argument list by
    /// <c>Table.GetFunc</c>, so <c>anime.getname(lang)</c> and <c>anime.getname(lang, unofficial)</c> both work.
    /// </summary>
    private void EmitCallable(StringBuilder sb, string name, Type delegateType, char sep)
    {
        ParameterInfo[] parameters = delegateType.GetMethod("Invoke")!.GetParameters();
        IEnumerable<string> pars = parameters.Select(p => IsOptional(p) ? $"string? {p.Name} = null" : $"string {p.Name}");
        IEnumerable<string?> args = parameters.Select(p => p.Name);
        _ = sb.Append($"    public string {name}({string.Join(", ", pars)}) => GetFunc([{string.Join(", ", args)}], '{sep}');\n");
    }

    private bool IsOptional(ParameterInfo p) =>
        Nullable.GetUnderlyingType(p.ParameterType) is not null || _nullability.Create(p) is { WriteState: NullabilityState.Nullable };

    private static void EmitNavProp(StringBuilder sb, string name, Type t)
    {
        const string getCall = "Get()";

        // Enum table -> NamesEnum<TEnum>, so `Env.Language[TitleLanguage.English]` renders "Language.English".
        if (SchemaReflection.IsEnumTable(t))
        {
            _ = sb.Append($"    public {Bt}.NamesEnum<global::{t.GetGenericArguments()[0].FullName}> {name} => new() {{ Path = {getCall} }};\n");
            return;
        }

        // List of models -> NamesArray<TNames>, so `Env.episodes[1]` renders "episodes[1]".
        if (SchemaReflection.ListElement(t) is { } elem && SchemaReflection.IsLuaModel(elem))
        {
            _ = sb.Append($"    public {Bt}.NamesArray<{ModelToNames(elem.Name)}> {name} => new() {{ Path = {getCall} }};\n");
            return;
        }

        // Nested model (incl. nullable reference like DateTimeModel?) -> navigable nav property.
        if (SchemaReflection.IsLuaModel(t))
        {
            _ = sb.Append($"    public {ModelToNames(t.Name)} {name} => new() {{ Path = {getCall} }};\n");
            return;
        }

        // Everything else (scalars, enums, scalar lists, scalar dicts, LuaUnion) -> leaf string.
        _ = sb.Append($"    public string {name} => {getCall};\n");
    }

    private static string ModelToNames(string name) => SchemaReflection.StripModel(name) + "Names";
}
