using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LuaRenamer.NamesGenerator
{
    /// <summary>
    /// Emits <c>*Names</c> companion classes for each <c>ILuaModel</c> record in the env schema.
    /// The navigation DSL allows Lua path strings to be built in a compiler-checked, type-safe
    /// manner (e.g. <c>EnvNames.anime.relations[1].type</c> produces the string
    /// <c>"anime.relations[1].type"</c>).
    ///
    /// Driven by the plain-CLR <c>ILuaModel</c> records (IReadOnlyList&lt;T&gt;, IReadOnlyDictionary&lt;K,V&gt;,
    /// nested models, enums, LuaFn&lt;TDelegate&gt;) rather than the old <c>*Table</c> writer classes and
    /// their LuaRef/LuaArray/LuaMap/LuaEnumRef carriers.
    ///
    /// NOTE: targets C# 7.3 (the supported language version for netstandard2.0 analyzers), so this
    /// source avoids raw string literals, file-scoped namespaces, property patterns, NRT, etc.
    /// </summary>
    [Generator]
    public class NamesGenerator : IIncrementalGenerator
    {
        // Namespace the ILuaModel records live in (the generator input).
        private const string Ns = "LuaRenamer.LuaEnv";

        // Namespace/base of the emitted DSL (the generator output) — unchanged.
        private const string Bt = "global::LuaRenamer.LuaEnv.Names";

        private const string BaseTypesSource = @"// <auto-generated/>
#nullable enable
using System.Linq;
using System.Runtime.CompilerServices;

namespace LuaRenamer.LuaEnv.Names;

public class Table
{
    public string Fn { get; init; } = """";
    public override string ToString() => Fn;
    protected string Get(char sep = '.', [CallerMemberName] string memberName = """") => string.IsNullOrEmpty(Fn) ? memberName : Fn + sep + memberName;
    protected string GetFunc(string?[] args, char sep = '.', [CallerMemberName] string memberName = """") =>
        Get(sep, memberName) + ""("" + string.Join("", "", args.TakeWhile(a => !string.IsNullOrWhiteSpace(a))) + "")"";
}

public class ArrayTable<T> : Table where T : Table, new()
{
    public T this[int index] => new() { Fn = Fn + $""[{index}]"" };
}

public class EnumTable<T> : Table where T : System.Enum
{
    public string this[T enumValue] => $""{Fn}.{enumValue}"";
}";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("LuaNavBaseTypes.g.cs", SourceText.From(BaseTypesSource, Encoding.UTF8));
            });

            var source = context.CompilationProvider.Select((compilation, _) => Build(compilation));
            context.RegisterSourceOutput(source, (spc, src) =>
            {
                if (src != null)
                    spc.AddSource("LuaNames.g.cs", SourceText.From(src, Encoding.UTF8));
            });
        }

        private static string Build(Compilation compilation)
        {
            var ns = GetNamespace(compilation.GlobalNamespace, Ns.Split('.'));
            if (ns == null)
                return null;

            var types = ns.GetTypeMembers().Where(t => t.TypeKind == TypeKind.Class).ToList();

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n\n");
            sb.Append("namespace LuaRenamer.LuaEnv.Names;\n\n");

            foreach (var t in types.OrderBy(t => t.Name, StringComparer.Ordinal))
            {
                if (ImplementsILuaModel(t))
                    EmitNames(sb, t);
            }

            return sb.ToString();
        }

        private static void EmitNames(StringBuilder sb, INamedTypeSymbol type)
        {
            var namesClass = ModelToNames(type.Name);

            sb.Append($"public sealed class {namesClass} : {Bt}.Table\n{{\n");

            foreach (var member in type.GetMembers())
            {
                var prop = member as IPropertySymbol;
                if (prop == null)
                    continue;
                var fieldAttr = GetAttr(prop, "LuaFieldAttribute");
                if (fieldAttr == null)
                    continue;

                // Callable field: LuaFn<TDelegate> with [LuaField]. ':' method-call syntax when
                // [LuaField(Method = true)], '.' plain-function syntax otherwise.
                var funcRef = prop.Type as INamedTypeSymbol;
                if (funcRef != null
                    && funcRef.Name == "LuaFn"
                    && funcRef.TypeArguments.Length == 1
                    && funcRef.TypeArguments[0] is INamedTypeSymbol del
                    && del.DelegateInvokeMethod != null)
                {
                    var invoke = del.DelegateInvokeMethod;
                    var pars = new List<string>();
                    var args = new List<string>();
                    foreach (var param in invoke.Parameters)
                    {
                        var paramNamed = param.Type as INamedTypeSymbol;
                        var isNull = (paramNamed != null && paramNamed.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                            || param.NullableAnnotation == NullableAnnotation.Annotated;
                        var name = param.Name;
                        pars.Add(isNull ? $"string? {name} = null" : $"string {name}");
                        args.Add(name);
                    }
                    var sep = GetBoolNamedArg(fieldAttr, "Method") ? ":" : ".";
                    var body = $"GetFunc([{string.Join(", ", args)}], '{sep}')";
                    sb.Append($"    public string {prop.Name}({string.Join(", ", pars)}) => {body};\n");
                }
                else
                {
                    EmitNavProp(sb, prop.Name, prop.Type);
                }
            }

            sb.Append("}\n\n");
        }

        private static void EmitNavProp(StringBuilder sb, string name, ITypeSymbol ts)
        {
            const string getCall = "Get()";
            var named = ts as INamedTypeSymbol;

            // Enum table: IReadOnlyDictionary<TEnum, TEnum> (key type == value type, an enum) -> EnumTable<TEnum>.
            // Distinguishes the identity enum maps from scalar dictionaries like illegal_chars_map (<string,string>).
            if (named != null
                && named.Name == "IReadOnlyDictionary"
                && named.TypeArguments.Length == 2
                && SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], named.TypeArguments[1])
                && named.TypeArguments[0].TypeKind == TypeKind.Enum)
            {
                var fqEnum = named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.Append($"    public {Bt}.EnumTable<{fqEnum}> {name} => new() {{ Fn = {getCall} }};\n");
                return;
            }

            // List of models (IReadOnlyList/Collection/IEnumerable<TModel> or TModel[]) -> ArrayTable<TModelNames>.
            var elem = ListElement(ts);
            if (elem != null && ImplementsILuaModel(elem))
            {
                sb.Append($"    public {Bt}.ArrayTable<{ModelToNames(elem.Name)}> {name} => new() {{ Fn = {getCall} }};\n");
                return;
            }

            // Nested model (incl. nullable reference like DateTimeModel?) -> navigable nav property.
            if (ImplementsILuaModel(ts))
            {
                sb.Append($"    public {ModelToNames(ts.Name)} {name} => new() {{ Fn = {getCall} }};\n");
                return;
            }

            // Everything else (scalars, enums, scalar lists, scalar dicts, LuaUnion) -> leaf string.
            sb.Append($"    public string {name} => {getCall};\n");
        }

        // The element type of an array / IReadOnlyList<T> / IReadOnlyCollection<T> / IEnumerable<T>, else null.
        private static ITypeSymbol ListElement(ITypeSymbol t)
        {
            var arr = t as IArrayTypeSymbol;
            if (arr != null)
                return arr.ElementType;
            var named = t as INamedTypeSymbol;
            if (named != null && named.TypeArguments.Length == 1
                && (named.Name == "IReadOnlyList" || named.Name == "IReadOnlyCollection" || named.Name == "IEnumerable"))
                return named.TypeArguments[0];
            return null;
        }

        private static string ModelToNames(string name) =>
            name.EndsWith("Model") ? name.Substring(0, name.Length - 5) + "Names" : name + "Names";

        private static bool ImplementsILuaModel(ITypeSymbol type) =>
            type.AllInterfaces.Any(i => i.Name == "ILuaModel");

        private static AttributeData GetAttr(ISymbol s, string attrName) =>
            s.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attrName);

        private static bool GetBoolNamedArg(AttributeData attr, string name)
        {
            foreach (var na in attr.NamedArguments)
                if (na.Key == name && na.Value.Value is bool b)
                    return b;
            return false;
        }

        private static INamespaceSymbol GetNamespace(INamespaceSymbol root, IEnumerable<string> parts)
        {
            var current = root;
            foreach (var part in parts)
            {
                current = current.GetNamespaceMembers().FirstOrDefault(n => n.Name == part);
                if (current == null)
                    return null;
            }
            return current;
        }
    }
}
