using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LuaBuilderGenerator;

/// <summary>
/// Emits strongly-typed builder classes (one per schema <c>*Table</c>/<c>RootTable</c>) into the
/// LuaRenamer compilation. Each builder exposes one fluent setter per field whose parameter type is
/// derived from the field's <c>[LuaType]</c> annotation, giving compile-time type-safe binding into
/// the underlying untyped <c>NLua.LuaTable</c>. The schema classes remain the single source of truth.
/// </summary>
[Generator]
public class BuilderGenerator : IIncrementalGenerator
{
    private const string Ns = "LuaRenamer.LuaEnv";
    private const string Bt = "global::LuaRenamer.LuaEnv.BaseTypes";
    private const string LuaTable = "global::NLua.LuaTable";
    private const string LuaFunction = "global::NLua.LuaFunction";

    private static readonly SymbolDisplayFormat Fq = SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider.Select(static (compilation, _) => Build(compilation));
        context.RegisterSourceOutput(source, static (spc, src) =>
        {
            if (src is not null)
                spc.AddSource("LuaBuilders.g.cs", SourceText.From(src, Encoding.UTF8));
        });
    }

    private static string? Build(Compilation compilation)
    {
        var ns = GetNamespace(compilation.GlobalNamespace, Ns.Split('.'));
        if (ns is null)
            return null;

        var types = ns.GetTypeMembers().Where(t => t.TypeKind == TypeKind.Class).ToList();

        // Map: Lua type name (e.g. "Anime") -> the *Table class symbol (class-level [LuaType]).
        var tableByLua = new Dictionary<string, INamedTypeSymbol>();
        foreach (var t in types)
            if (GetLuaType(t) is { } attr && GetString(attr, 0) is { } luaName)
                tableByLua[luaName] = t;

        // Map: Lua enum name (e.g. "Language") -> CLR enum type, read from EnumsTable's EnumTable<T> props.
        var enumByLua = new Dictionary<string, ITypeSymbol>();
        var enumsTable = types.FirstOrDefault(t => t.Name == "EnumsTable");
        if (enumsTable is not null)
            foreach (var p in enumsTable.GetMembers().OfType<IPropertySymbol>())
                if (p.Type is INamedTypeSymbol { OriginalDefinition.Name: "EnumTable", TypeArguments.Length: 1 } et)
                    enumByLua[p.Name] = et.TypeArguments[0];

        var map = new TypeMapper(tableByLua, enumByLua);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n\n");
        sb.Append("namespace LuaRenamer.LuaEnv.Builders;\n\n");

        foreach (var t in types.OrderBy(t => t.Name, System.StringComparer.Ordinal))
        {
            var isTable = GetLuaType(t) is not null;
            var isRoot = t.BaseType?.Name == "RootTable";
            if (!isTable && !isRoot)
                continue;
            EmitBuilder(sb, t, map, isTable);
        }

        return sb.ToString();
    }

    private static void EmitBuilder(StringBuilder sb, INamedTypeSymbol type, TypeMapper map, bool isTable)
    {
        var className = type.Name;
        var typeFqn = type.ToDisplayString(Fq);
        var builderName = $"{className}Builder";

        sb.Append($"internal sealed class {builderName}\n{{\n");
        sb.Append($"    private readonly {LuaTable} _t;\n\n");
        sb.Append($"    public {builderName}({LuaTable} table)\n    {{\n        _t = table;\n");
        if (type.GetMembers("_classidVal").OfType<IFieldSymbol>().Any(f => f.IsConst))
            sb.Append($"        _t[\"_classid\"] = {typeFqn}._classidVal;\n");
        sb.Append("    }\n\n");

        foreach (var member in type.GetMembers())
        {
            switch (member)
            {
                case IPropertySymbol prop when GetLuaType(prop) is { } attr:
                {
                    if (GetBool(attr, "Output"))
                        continue;
                    var luaType = GetString(attr, 0)!;
                    var (paramType, assign) = map.Map(luaType);
                    EmitSetter(sb, builderName, prop.Name, paramType, $"_t[\"{prop.Name}\"] = {assign};");
                    break;
                }
                case IMethodSymbol { MethodKind: MethodKind.Ordinary } method when GetLuaType(method) is not null:
                {
                    EmitSetter(sb, builderName, method.Name, LuaFunction, $"_t[\"{method.Name}\"] = v;");
                    break;
                }
                // Enum globals (EnumsTable): EnumTable<T> properties carry no [LuaType].
                case IPropertySymbol { Type: INamedTypeSymbol { OriginalDefinition.Name: "EnumTable", TypeArguments.Length: 1 } et } enumProp
                    when GetLuaType(enumProp) is null:
                {
                    var enumFqn = et.TypeArguments[0].ToDisplayString(Fq);
                    EmitSetter(sb, builderName, enumProp.Name, $"{Bt}.LuaEnumRef<{enumFqn}>", $"_t[\"{enumProp.Name}\"] = v.Table;");
                    break;
                }
            }
        }

        if (isTable)
            sb.Append($"    public {Bt}.LuaRef<{typeFqn}> Build() => new(_t);\n");
        else
            sb.Append($"    public {LuaTable} Build() => _t;\n");
        sb.Append("}\n\n");
    }

    private static void EmitSetter(StringBuilder sb, string builderName, string name, string paramType, string body) =>
        sb.Append($"    public {builderName} {name}({paramType} v) {{ {body} return this; }}\n");

    private static AttributeData? GetLuaType(ISymbol symbol) =>
        symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "LuaTypeAttribute");

    private static string? GetString(AttributeData attr, int index) =>
        attr.ConstructorArguments.Length > index ? attr.ConstructorArguments[index].Value as string : null;

    private static bool GetBool(AttributeData attr, string name) =>
        attr.NamedArguments.FirstOrDefault(n => n.Key == name).Value.Value is true;

    private static INamespaceSymbol? GetNamespace(INamespaceSymbol root, string[] parts)
    {
        var current = root;
        foreach (var part in parts)
        {
            current = current.GetNamespaceMembers().FirstOrDefault(n => n.Name == part);
            if (current is null)
                return null;
        }

        return current;
    }
}

/// <summary>Maps a Lua type annotation string to a C# parameter type and the assignment expression
/// (in terms of the parameter named <c>v</c>) used to write the value into the LuaTable.</summary>
internal sealed class TypeMapper(
    Dictionary<string, INamedTypeSymbol> tableByLua,
    Dictionary<string, ITypeSymbol> enumByLua)
{
    private static readonly SymbolDisplayFormat Fq = SymbolDisplayFormat.FullyQualifiedFormat;
    private const string Bt = "global::LuaRenamer.LuaEnv.BaseTypes";

    public (string ParamType, string Assign) Map(string lua)
    {
        var nullable = false;
        if (lua.EndsWith("|nil"))
        {
            nullable = true;
            lua = lua.Substring(0, lua.Length - 4);
        }

        if (lua.EndsWith("[]"))
        {
            var elem = ElementType(lua.Substring(0, lua.Length - 2));
            return ($"{Bt}.LuaArray<{elem}>{(nullable ? "?" : "")}", nullable ? "v?.Table" : "v.Table");
        }

        if (lua.StartsWith("table<") && lua.EndsWith(">"))
        {
            var inner = lua.Substring(6, lua.Length - 7);
            var comma = inner.IndexOf(',');
            var k = Scalar(inner.Substring(0, comma).Trim());
            var val = Scalar(inner.Substring(comma + 1).Trim());
            return ($"{Bt}.LuaMap<{k}, {val}>{(nullable ? "?" : "")}", nullable ? "v?.Table" : "v.Table");
        }

        switch (lua)
        {
            case "number": return ($"double{(nullable ? "?" : "")}", "v");
            case "integer": return ($"long{(nullable ? "?" : "")}", "v");
            case "boolean": return ($"bool{(nullable ? "?" : "")}", "v");
            case "string": return ($"string{(nullable ? "?" : "")}", "v");
        }

        if (enumByLua.TryGetValue(lua, out var enumSym))
            return ($"{enumSym.ToDisplayString(Fq)}{(nullable ? "?" : "")}", nullable ? "v?.ToString()" : "v.ToString()");

        if (tableByLua.TryGetValue(lua, out var tableSym))
            return ($"{Bt}.LuaRef<{tableSym.ToDisplayString(Fq)}>{(nullable ? "?" : "")}", nullable ? "v?.Table" : "v.Table");

        return ($"object{(nullable ? "?" : "")}", "v");
    }

    // The generic element type of LuaArray<T> for a "T[]" field.
    private string ElementType(string elem) => elem switch
    {
        "string" => "string",
        "integer" => "long",
        "number" => "double",
        "boolean" => "bool",
        _ when enumByLua.TryGetValue(elem, out var e) => e.ToDisplayString(Fq),
        _ when tableByLua.TryGetValue(elem, out var t) => $"{Bt}.LuaRef<{t.ToDisplayString(Fq)}>",
        _ => "object",
    };

    // A generic type argument of LuaMap<K, V> for a key/value token of a "table<K, V>" field.
    private string Scalar(string token) => token switch
    {
        "string" => "string",
        "integer" => "long",
        "number" => "double",
        "boolean" => "bool",
        _ when enumByLua.TryGetValue(token, out var e) => e.ToDisplayString(Fq),
        _ when tableByLua.TryGetValue(token, out var t) => $"{Bt}.LuaRef<{t.ToDisplayString(Fq)}>",
        _ => "object",
    };
}
