using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LuaBuilderGenerator;

/// <summary>
/// Emits <c>*Names</c> companion classes for each <c>*Table</c> schema class.
/// The navigation DSL allows Lua path strings to be built in a compiler-checked, type-safe
/// manner (e.g. <c>EnvNames.anime.relations[1].type</c> produces the string
/// <c>"anime.relations[1].type"</c>). This replaces the hand-written table classes that
/// previously doubled as both schema and navigation.
/// </summary>
[Generator]
public class NamesGenerator : IIncrementalGenerator
{
    private const string Ns = "LuaRenamer.LuaEnv";
    private const string Bt = "global::LuaRenamer.LuaEnv.BaseTypes";

    private static readonly SymbolDisplayFormat FqNullable = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider.Select(static (compilation, _) => Build(compilation));
        context.RegisterSourceOutput(source, static (spc, src) =>
        {
            if (src is not null)
                spc.AddSource("LuaNames.g.cs", SourceText.From(src, Encoding.UTF8));
        });
    }

    private static string? Build(Compilation compilation)
    {
        var ns = GetNamespace(compilation.GlobalNamespace, Ns.Split('.'));
        if (ns is null)
            return null;

        var types = ns.GetTypeMembers().Where(t => t.TypeKind == TypeKind.Class).ToList();

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n\n");
        sb.Append("namespace LuaRenamer.LuaEnv.Names;\n\n");

        foreach (var t in types.OrderBy(t => t.Name, System.StringComparer.Ordinal))
        {
            var isTable = t.GetAttributes().Any(a => a.AttributeClass?.Name == "LuaTypeAttribute");
            var isRoot = t.BaseType?.Name is "RootTable" or "LuaRootTableWriter";

            if (!isTable && !isRoot)
                continue;

            // Skip RootTable subclasses with no [LuaField] members (i.e. EnumsTable).
            if (isRoot && !t.GetMembers().OfType<IPropertySymbol>()
                    .Any(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "LuaFieldAttribute")))
                continue;

            EmitNames(sb, t, isRoot);
        }

        return sb.ToString();
    }

    private static void EmitNames(StringBuilder sb, INamedTypeSymbol type, bool isRoot)
    {
        var namesClass = TableToNames(type.Name);
        var baseClass = isRoot ? $"{Bt}.RootTable" : $"{Bt}.Table";

        sb.Append($"public sealed class {namesClass} : {baseClass}\n{{\n");

        foreach (var member in type.GetMembers())
        {
            var staticKw = isRoot ? "static " : "";

            switch (member)
            {
                // Bound data field: [LuaField] on a property.
                case IPropertySymbol prop when GetAttr(prop, "LuaFieldAttribute") is not null:
                {
                    if (GetBool(GetAttr(prop, "LuaFieldAttribute")!, "Output"))
                        continue;
                    EmitNavProp(sb, prop.Name, prop.Type, staticKw);
                    break;
                }
                // Output field with complex union Lua type — still a leaf string navigation property.
                case IPropertySymbol prop when GetAttr(prop, "LuaTypeAttribute") is { } typeAttr && GetBool(typeAttr, "Output"):
                    sb.Append($"    public {staticKw}string {prop.Name} => Get();\n");
                    break;
                // Function binding property: [LuaType(function)] on a Func/Action property.
                case IPropertySymbol prop when GetAttr(prop, "LuaTypeAttribute") is not null
                    && prop.Type is INamedTypeSymbol { Name: "Func" or "Action" }:
                {
                    var paramAttrs = prop.GetAttributes()
                        .Where(a => a.AttributeClass?.Name == "LuaParameterAttribute")
                        .Select(a => a.ConstructorArguments.Length > 0 ? a.ConstructorArguments[0].Value as string ?? "" : "")
                        .ToList();
                    var paramList = string.Join(", ", paramAttrs.Select(n => $"string {n}"));
                    var argArray = string.Join(", ", paramAttrs);
                    var body = isRoot ? $"GetFunc([{argArray}])" : $"GetFunc([{argArray}], ':')";
                    sb.Append($"    public {staticKw}string {prop.Name}({paramList}) => {body};\n");
                    break;
                }
                // Function member: [LuaType(function)] on an ordinary method.
                case IMethodSymbol { MethodKind: MethodKind.Ordinary } method when GetAttr(method, "LuaTypeAttribute") is not null:
                {
                    var paramList = string.Join(", ", method.Parameters.Select(FormatParam));
                    var argArray = string.Join(", ", method.Parameters.Select(p => p.Name));
                    // Root functions are called with () syntax; instance methods use : syntax in Lua.
                    var body = isRoot
                        ? $"GetFunc([{argArray}])"
                        : $"GetFunc([{argArray}], ':')";
                    sb.Append($"    public {staticKw}string {method.Name}({paramList}) => {body};\n");
                    break;
                }
            }
        }

        sb.Append("}\n\n");
    }

    private static void EmitNavProp(StringBuilder sb, string name, ITypeSymbol ts, string staticKw)
    {
        // Nullable<T> wrapping a struct (LuaRef<T>?, long?, enum?, bool?)
        if (ts is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullSym)
        {
            var inner = nullSym.TypeArguments[0];
            if (inner is INamedTypeSymbol { Name: "LuaRef", TypeArguments.Length: 1 } luaRef)
            {
                // LuaRef<T>? — always emitted as a navigable (non-nullable) nav property.
                var navType = TableToNames(luaRef.TypeArguments[0].Name);
                sb.Append($"    public {staticKw}{navType} {name} => new() {{ Fn = Get() }};\n");
                return;
            }
            // Scalar? (long?, bool?, enum?) — leaf string.
            sb.Append($"    public {staticKw}string {name} => Get();\n");
            return;
        }

        if (ts is INamedTypeSymbol named)
        {
            switch (named.Name)
            {
                case "LuaRef" when named.TypeArguments.Length == 1:
                {
                    var navType = TableToNames(named.TypeArguments[0].Name);
                    sb.Append($"    public {staticKw}{navType} {name} => new() {{ Fn = Get() }};\n");
                    return;
                }
                case "LuaArray" when named.TypeArguments.Length == 1:
                {
                    var elem = named.TypeArguments[0];
                    if (elem is INamedTypeSymbol { Name: "LuaRef", TypeArguments.Length: 1 } elemRef)
                    {
                        var elemNav = TableToNames(elemRef.TypeArguments[0].Name);
                        sb.Append($"    public {staticKw}{Bt}.ArrayTable<{elemNav}> {name} => new() {{ Fn = Get() }};\n");
                        return;
                    }
                    // LuaArray<scalar> — leaf string.
                    sb.Append($"    public {staticKw}string {name} => Get();\n");
                    return;
                }
                case "LuaMap":
                    sb.Append($"    public {staticKw}string {name} => Get();\n");
                    return;
            }
        }

        // Scalars (long, double, bool, string, string?, enum) — leaf string.
        sb.Append($"    public {staticKw}string {name} => Get();\n");
    }

    private static string FormatParam(IParameterSymbol p)
    {
        var typeStr = p.Type.ToDisplayString(FqNullable);
        return p.HasExplicitDefaultValue
            ? $"{typeStr} {p.Name} = {(p.ExplicitDefaultValue is null ? "null" : $"\"{p.ExplicitDefaultValue}\"")}"
            : $"{typeStr} {p.Name}";
    }

    private static string TableToNames(string name) =>
        name.EndsWith("Table") ? name.Substring(0, name.Length - 5) + "Names" : name + "Names";

    private static AttributeData? GetAttr(ISymbol s, string attrName) =>
        s.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attrName);

    private static bool GetBool(AttributeData attr, string name) =>
        attr.NamedArguments.FirstOrDefault(n => n.Key == name).Value.Value is true;

    private static INamespaceSymbol? GetNamespace(INamespaceSymbol root, IEnumerable<string> parts)
    {
        var current = root;
        foreach (var part in parts)
        {
            current = current.GetNamespaceMembers().FirstOrDefault(n => n.Name == part);
            if (current is null)
                return null;
        }
        return current;
    }
}
