name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.nuget/packages
          antlr-4.9-complete.jar
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Download antlr4
      run: |
        test -f antlr-4.9-complete.jar || curl -O https://www.antlr.org/download/antlr-4.9-complete.jar
        printf '#!/bin/bash\njava -cp "$GITHUB_WORKSPACE/antlr-4.9-complete.jar" -Xmx500M org.antlr.v4.Tool $@\n' | sudo tee /usr/bin/antlr4
        sudo chmod +x /usr/bin/antlr4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
