name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.nuget/packages
          antlr-4.9-complete.jar
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Download & run antlr4
      run: |
        test -f antlr-4.9-complete.jar && curl -O https://www.antlr.org/download/antlr-4.9-complete.jar
        java -cp "antlr-4.9-complete.jar" org.antlr.v4.Tool -Dlanguage=CSharp -visitor -no-listener $GITHUB_WORKSPACE/ScriptRenamer/ScriptRenamer.g4 -o $GITHUB_WORKSPACE/ScriptRenamer/GeneratedCode
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
