name: Publish Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: |
        for rid in "win-x64" "linux-x64" "linux-arm64"; do
          dotnet publish ./LuaRenamer/LuaRenamer.csproj -c Release -r "$rid" -o "./publish/$rid"
        done
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "$GITHUB_REF_NAME" ./publish/*.zip --generate-notes --verify-tag --prerelease
